### PR TITLE
Set up switching in gw_drag code

### LINKED ISSUE #8: Set up switching based on namelist parameter in code
As detailed in #2 we should modify the code in gw_drag.f90 to call the alternative ML code.

- retrieve namelist variable for switch
- if clause around routines to call as appropriate
- logic to only apply the relevant updates for the ongoing simulation

### PR DESCRIPTION
**Pull request by jatkinson1000**
Closes #8 

Note that this is build on top of (rebased) #4 and #5 

Modifications the code in gw_drag.f90 in preparation to call the alternative ML code.

- [x] retrieve namelist variable for switch
- [x] if clause around routines to call as appropriate
- [x] logic to only apply the relevant updates for the ongoing simulation

### CODE REVIEW

**Comment by jatkinson1000** [comment]
For  implementing the case correctly we need to know what and where the CAM state variables are updated.

Is it as part of `gw_drag_prof()` which will complicate things, or is it an output from this routine that is applied somewhere subsequently?

My understanding is that `utgw` and `vtgw` are `intent(out)` from gw_drag_prof() so could be written to file and overwritten by another scheme.

**Comment by jatkinson1000** [comment]
Yes, these variables are tendencies that are added to a `ptend` variable for u and v a few lines later, so can hopefully be overwritten as appropriate.

**Comment by jatkinson1000** [comment]
This has been updated so that the logic is in place for the different options to be run.
Currently they all call the non-ML scheme, with a `TODO` in-code for modifying later once the coupling interface is written.
See comments above regarding where the tendencies are added to `ptend` - will require additional logic loops to select which is run.

**Review by yqsun91 — APPROVED** [review]

**Review by yqsun91 — APPROVED** [review]

**Review by surbhigoel77 — APPROVED** [review]

**Review by yqsun91 — APPROVED** [review]
I have gone through this and all look good to me.

**Pull request merged**
